---
title: 3ⁿグルーヴ理論とは
created: 2025-05-27T11:08
tags:
  - foo
---
<script>
  document.addEventListener("DOMContentLoaded", () => {
    document.querySelectorAll(".ats4u-twitter-video").forEach((el) => {
      const twitterId = (el.innerText)?.replaceAll?.( "x.com", "twitter.com" );
      if (twitterId !== null) {
        el.outerHTML = (`<blockquote class="twitter-tweet" data-conversation="none" data-media-max-width="560"><a href="${twitterId}">${twitterId}</a></blockquote>` );
      }
    });
  });
</script>

## 世界は3拍子で出来ている

[CV Phonology A Generative Theory of the Syllable](https://mitpress.mit.edu/9780262530477/cv-phonology/)

CV音韻分析（1983年） 私はいつも「日本語には末子音がない」と言っていることには、子音と母音の並びを分析することで言語自体が持っているリズムの特性を分析出来ると私が考えていることによる。これは私が勝手に考えたことでは決してなく、1983年に既にCV音韻分析という言語の音韻分析に大きな影響を与えた論文がある。単に日本の言語学でほとんど知られていないだけだ。─── CV Phonology A Generative Theory of the Syllable

### 何故世界の音楽は三拍子で出来ているのか。そして何故日本人は三拍子が聴き取れないのか。
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1878808994623713704</div>

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">ドビュッシーの月の光は 9/8 で書かれていることに気付きました。私がいつも言っている「3連符3拍子」は、歴史的に正しくは 9/8 と呼ばれているのかも知れない…と思いました。<br><br>少しだけ調べてみたら「9/8 は 6/8 の仲間のリズム」 という説明が見つかりました。… <a href="https://t.co/1U8vUctp9v">pic.twitter.com/1U8vUctp9v</a></p>&mdash; 岡敦/Ats🇯🇵 (@ats4u) <a href="https://twitter.com/ats4u/status/1741136150394458596?ref_src=twsrc%5Etfw">December 30, 2023</a></blockquote>

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1766696559637647609</div>

https://chatgpt.com/c/684050f7-d864-8013-a6d8-cc29274882b3

### 月の光（チッコリーニ）
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1680263197268520960</div>

### Terry Reiley の The Padova Concert から The Discovery
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1680263993892700160</div>

### Philip Tagg 先生が作ったスコッチスナップを使ったリズムの音楽
音楽史学者のフィリップ・タグ先生が作ったスコットランド民謡のリズムを使った音楽
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1680269367874060290</div>

### Inama - Diamond Platnumz ft Fally Ipupa
2020年頃にインターネットで世界的に流行したタンザニアのミュージシャン・ダイアモンド・プラチナムさんの音楽・Fally Ipupa氏をボーカリストとしてフューチャした。
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1680270246333284354</div>

### Pray for Me - Moses Tyson Jr.
ゴスペル音楽。モーゼス・タイソンJr. はスライ・ストーンのいとこで、スライストーン氏の進めでギターを弾き始めた12歳以来の長い経歴をもっている。
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1680270910929125377</div>

### Pray for Me - Richard Mr.Clean White
伝説的なゴスペルミュージシャンであり司教のリチャード・ミスタークリーン・ホワイト氏の演奏する Pray For Me

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1680271219118182401</div>

### Footprints · Miles Davis
マイルス・デイヴィスの名演・フットプリンツ
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1680271791103811584</div>

### Virgo - Wayne Shorter
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1680273677647228929</div>

### But Beautiful - Grant Green

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1680274200152653824</div>

### Moses Tyson Jr. / Near the Cross
ゴスペルのスタンダード曲 Near the Cross は27/8拍子の曲です。
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1741136150394458596</div>

### Radiohead のCodex
小節長は変化しないままで 12/8 及び 9/8 を入れ替える、アフリカ南部の音楽とヨーロッパの民族ケルト族の一派であるゲール族の音楽に共通して現れるジャズの起源となったリズムが、レディオヘッドのこの曲にも表れます。

### Homecoming / John Abercrombie - The Gateway Trio
ジョン・アバークロンビーの The Gateway Trio の演奏で Homecoming です。27/8拍子＝アフリカの鼓動とゲールの魂のハイブリッド音楽 ─── この英語の根底に流れているリズムがジャズに反映されています。

<div class="ats4u-twitter-video" >https://x.com/raradiohead/status/1756867358457782735</div>

### ゴスペルのスタンダード曲 God will Supply

God will Supply サブディヴィジョンが 3x3x3 で構成される 27/8 拍子です。
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1766688387015360780</div>

### ニア・ザ・クロス／ミシシッピ・マス・クワイア（コーラス）
ニア・ザ・クロス／ミシシッピ・マス・クワイア（コーラス）The Mississippi Mass Choir - Near The Cross ／Credit : Malaco Music [https://t.co/c2UXcARa8D](https://t.co/c2UXcARa8D)

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1766685980965355523</div>

### ウォーク・イン・ザ・ライト／モーゼス・タイソン・Ｊｒ
【27/8拍子＝アフリカの鼓動とゲールの魂のハイブリッド音楽 ─── それがジャズ】 3小節/3拍子/3連符=27/8 拍子の名曲です。 モーゼス・タイソン・Ｊｒ ウォーク・イン・ザ・ライト Credit :Walk In The Light Moses Tyson Jr.

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1766798603752984792</div>

### ウォーク・イン・ザ・ライト／アレサ・フランクリン
【27/8拍子＝アフリカの鼓動とゲールの魂のハイブリッド音楽 ─── それがジャズ】ウォーク・イン・ザ・ライト／アレサ・フランクリン（1987年のライブ演奏）

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1766806553754267959</div>

### チャイコフスキー交響曲第4番第1楽章
チャイコフスキー交響曲第4番第1楽章は、3拍子16分音符／スコッチスナップ／尻合わせリズムが多用されています。 ロシア国立交響楽団／指揮ターイェ・ミッケルセン（ノルウェー）State Academic Symphony Orchestra of Russia, conductor Terje Mikkelsen, Symphony No.4, 1st movement [https://youtube.com/watch?v=iE9LhoKEmBk](https://t.co/LYUADKSMG8)

### Zone III (Live) / Then! / Then! (Remastered) Allan Holdsworth

アラン・ホールズワースの Zone III という即興曲です。 アルバム Then! に収録されています。 これは 16分音符/3拍子/3小節で構成されるリズムです。これはつまり 72/16= 8x3x3/16 という拍子で 12/8 を拡張したリズムともいえます。 Zone III (Live) / Then! / Then! (Remastered) Allan Holdsworth [https://](https://t.co/DeQa8DiFG8)

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1767900994594329066</div>

### ホーリー・ワン Dominique Johnson / Holy one
無名のB3オルガンの名人・ドミニク・ジョンソン氏の演奏でホーリーワンです。
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1738530936629702844</div>

### アナイシャのホーリーワン
Anaysha - Holy One
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1738529775860559881</div>

### トラマイン・ホーキンスのホーリーワン

実は、HOLY ONE のオリジナル演奏者は、このトラマイン・ホーキンスなのだそうです。 この演奏は、更に、更にパワフルな演奏でしたしかも、もう遥か昔に絶版になり存在も確認出来ない様な無名のアルバムです。 Tramaine Hawkins Holy One [https://youtube.com/watch?v=QAbIVf](https://t.co/ZJ3HCpUkQc)

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1781164917103739124</div>

### ラオス民族音楽ラム・バンラン・シヤンラカントーンの孫を育てる老人
ラオス民族音楽ラム ラムローンヤーオ・孫を育てる老人 タイ東北の監督・鬼才シーカンソーのプロデュース 歌・バンラン・シヤンラカントーン ลำล่องยาว ผู้เฒ่าเลี้ยงหลาน ชุด ติดไม้ติดมือ โดยสี คันโซ่ ลำโดย บันลังก์ เสียงระฆังทอง [https://youtube.com/watch?v=pNmazw](https://t.co/VQdGm4xWnp)
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1789647164345593947</div>

### ラオス民族音楽ラム スィウィト・チャオナー（農民の人生） 歌・チャウィワン・ダムヌン
ラオス民族音楽ラム スィウィト・チャオナー（農民の人生） 歌・チャウィワン・ダムヌン（民謡ラムの名人） ฉวีวรรณ ดำเนิน - ชีวิตชาวนา
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1789672874288333070</div>

### アラン・ホールズワースのプロトコスモス
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1821920572630298859</div>

### Radiohead / Daydreaming

このRadiohead - Daydreaming の映像が他の Radiohead の映像と一線を画している様に感じるのは、決して気のせいではなく、実はこの作品は米国の鬼才フィルム作家 Paul Thomas Anderson とのコラボ。
<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1625112830323347462</div>

### エンニオ・モリコーネ「インテルヴァッロ２」
Ennio Morricone – Intervallo II

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1841084562312417471</div>

### Wrapped Around Your Finger Dianne Reeves With Bob Belden Ensemble

譜面上は8分音符だが、ずれによってその三倍の速さでの三連符三拍子を表現する。これがラテンに於けるベース打点のニュアンスの基礎になる。 16分音符の裏拍位置が基準となり、8分音符の表拍位置が遅れる。 裏拍は短く切られ音の止まる位置で標準的な表拍の位置を表現する一方、表拍は遅れて長く弛緩した表情を表現する。

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1850896343910567959</div>

### ドン・プーレンのリッスン・トゥー・ザ・ピープル

譜面上は8分音符だが、ずれによってその三倍の速さでの三連符三拍子を表現する。これがラテンに於けるベース打点のニュアンスの基礎になる ─── その２ 【ラテンに於けるベース打点のニュアンスの基礎】16分音符の裏拍位置が基準となり、8分音符の表拍位置が遅れる。 裏拍は短く切られ、その音の止まる位置で標準的な表拍の位置を表現する一方、表拍は遅れて長く弛緩した表情を表現する。

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1850907350695399730</div>

### チッコリーニのジムノペディ１
チッコリーニのジムノペディ１ ─── 究極の三拍子のニュアンス チッコリーニのジムノペティ１ チッコリーニが85歳の時の演奏（2010年） ─── 極めて短い極めて衝撃的な演奏 [https://youtube.com/watch?v=0peXnO](https://t.co/cyItYnwDoO)

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1850905277513789534</div>

### John Taylor - Speak to Me 
イギリスの天才ジャズ・ピアニスト (1942〜2015 ) 幻の名盤 Decipher から Speak to Me スイングバラードの3連符を3拍子に見立て、更にその中を3で分割する 3^n リズムの実例になっている。Credit : [https://youtube.com/watch?v=k7mRBdhAtZc](https://t.co/ZEDGsfMoDg)

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1883461746985480443</div>

### ノルウェーのクランパスのマーチ
9/8 (3拍子３連符) が現れています。このリズムはインド・東南アジア・東アジアの民族音楽には表れないリズムです。 9/8 (しばしば27/8や36/8)は、アフリカとゲール(現スコットランド・アイルランド)の音楽によく見られます。

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1885722201229594748</div>

### Aphex Twin - QKThr 
Aphex Twin - QKThr
 
    （最初の1拍は休符）
    3|3|3 =9=3*3 (INTRO)
    4|4|5|5 =18=3 * 6
    3|2|2|3|2 =12 = 3*4
    3|3|3|3|3|3 =18 = 3*6 
    3|3|3|2|3|3 = 17 = 3* 6 -1
    3|3|3 =9=3*3 (OUTRO)
    (最後の3拍は休符)

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1885728333415288979</div>

### Bobo Stenson Trio -Dormattan 
Bobo Stenson Trio -Dormattan 北欧ジャズのフリーテンポの様に聴こえるリズムはしばしば 9/8 拍子で演奏されます。

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1885731982577217639</div>


### Spaceflight Simulator の旧テーマ曲

<div class="ats4u-twitter-video" >https://x.com/ats4u/status/1957084023928291419</div>

