---
title: 声出しオフビートカウント法
format: html
---
<style>
    table { 
        width : 100%;
        height : auto;
        table-layout: fixed;
        border-collapse: collapse;
    }
    table td {
        border: 1px solid gray;
        text-align : center;
    }
</style>

## はじめに

この本では**声出しオフビートカウント**の練習方法について説明します。

**声出しカウント**とは演奏中に声を出して拍数を数えることをいいます。この声出しカウントはとても大切な音楽基礎力トレーニングです。

**オフビートカウント**は八分音符ひとつ分早くカウントをすることをいいます。オフビートカウントはこの本の著者オカアツシが考案したカウント方法です。ジャズ／ゴスペル／ブルース／Ｒ＆Ｂを初めとしたアフリカ発祥の音楽の影響を受けたポップ音楽の演奏の基礎トレーニングに適しています。

オフビートカウントはジャズ等々のアフリカ発祥音楽の影響の重要な要素である**グルーヴ**を安定して生成することを重視したカウントメソッドです。

まず音楽の中に存在する色々な長さのオフビートの正体をオフビートカウントによって明らかにし、そしてそれを確実に身に付ける方法を説明します。以下で各種オフビートとそのカウント方法を順を追って見ていきます。

### 読み方について

いろいろなカウント方法を譜面で書き表すこともできますが、ここでは数字「０〜９」と「＆」「Ｅ」「Ａ」「・」で表現することでカウントメソッドを説明したいと思います。

|        |                            |
| ------ | -------------------------- |
| ０〜９ | ワン・ツー…（英語で読む）  |
| ＆     | エン（英語で読む＝アンド） |
| Ｅ     | イー                       |
| Ａ     | アー                       |
| ・     | （休み・読まない）         |

### 伝わりやすいリズムと伝わりづらいリズム

オフビートカウントの最終目標は**頭合わせリズム**を脱して**尻合わせリズム**を維持できるようになることです。

頭合わせとは**伝わりにくいリズム**のことです。

- ミュージシャン以外の人に理解されない
- よくわからないと言われる
- 自分でもリズミカルだと感じられない

一方、尻合わせリズムは**しっかり気持ちに伝わるリズム**のことです。

**しっかり気持ちに伝わるリズム**＝**尻合わせリズム**は、バンド仲間や仲の良い友達に伝わるだけでなく、全く知らない人や音楽に興味のない子供やお年寄りにも伝わります。その思いは国境や言語を超えて人に伝わってゆきます。そこに込められた思いに関わらず、その思いは誰にでも確実に伝わります。 ─── **しっかり気持ちに伝わるリズム**＝**尻合わせリズム**で演奏することさえできれば ─── 。

それが**頭合わせリズム**と**尻合わせリズム**の違いです。

頭合わせリズムと尻合わせリズムの違いには、とてもはっきりした数学的な性質が存在します。以下でその違いについて学んでいきます。

見方を変えると尻合わせリズムの正体は**グルーヴ**です。自分では激しくグルーヴしているつもりでも、リズムが頭合わせになってしまえば残念なことにグルーヴは無情に消えてしまいます。

しかし逆に、例えもしバンド演奏中にトラブルがあったとしても、冷静にリズムの尻合わせを維持することさえできれば、グルーヴは維持されます。そのグルーヴと共に、トラブルを乗り越えたその気持ちが確実にリスナに伝わるでしょう。

### リズムトレーニングの難しさについて

この本はまるで『誰でも簡単に筋肉ムキムキになる方法』の様なものです。実際のところ、筋肉ムキムキになる方法は実に簡単です。『毎日腕立て伏せを５００回最低２年続ける』 ─── とても簡単なことですが誰もできません。誰もがやれば強くなれると知っている。誰にでもできることだけども、現実にはほとんど誰もできません。

筋肉トレーニングは体力を消耗します。リズムトレーニングは体力は消耗しませんが、精神力を消耗します。リズムトレーニングを行うとその後しばらくは動けなくなるほど激しく疲れます。疲れなくなるには、慣れるまでしばらくの辛抱が必要です。

上達のするには地道に個人練習を続ける以外に方法はありませんが、なかなかひとりで練習を続けるのは難しいものです。そこで少しずつ都内各所でリズムトレ練習会を開いていこうと思っております。フェースブック／ツイッター／ブログなどで告知致しますので、その際はどうぞ宜しくお願い致します。

## 基本

### オンビートカウント

**オンビートカウント**とは、拍に直接数字を割り当てて拍数を数えることをいいます。

<table>
<tbody>
<tr>
<td>１<br />
（ワン）</td>
<td>２<br />
（ツー）</td>
<td>３<br />
（スリー）</td>
<td>４<br />
（フォー）</td>
</tr>
</tbody>
</table>

練習 オンビートカウントを使って好きな音楽に合わせて数えてみましょう。

### 小節入りカウント

**小節入りカウント**とは、拍数と一緒に小節数も数えることをいいます。次の例はオンビートカウントを小節入りで行ったところです。

<table>
<tbody>
<tr>
<td>１<br />
（ワン）</td>
<td>２<br />
（ツー）</td>
<td>３<br />
（スリー）</td>
<td>４<br />
（フォー）</td>
</tr>
<tr>
<td>２<br />
（ツー）</td>
<td>２<br />
（ツー）</td>
<td>３<br />
（スリー）</td>
<td>４<br />
（フォー）</td>
</tr>
<tr>
<td>３<br />
（スリー）</td>
<td>２<br />
（ツー）</td>
<td>３<br />
（スリー）</td>
<td>４<br />
（フォー）</td>
</tr>
<tr>
<td>４<br />
（フォー）</td>
<td>２<br />
（ツー）</td>
<td>３<br />
（スリー）</td>
<td>４<br />
（フォー）</td>
</tr>
</tbody>
</table>

練習 好きな音楽に合わせて数えてみましょう。

### ＆入りカウント

**＆入りカウント**とは数字の半分の位置で＆といいながら拍数を数えることをいいます。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
| １  | ＆  | ２  | ＆  | ３  | ＆  | ４  | ＆  |

練習 好きな音楽に合わせて数えてみましょう。

### オフビートカウント

この**オフビートカウント**が当書の最も大切なカウント法になります。以下様々なパターンでオフビートカウントを応用していきます。ここでしっかりとオフビートカウントを学んでください。

**オフビートカウント**とはオンビートカウントと同じことを半ブロック早く行うことをいいます。これまでは拍と同時に数字を数えてきました。もし拍と同時に手を叩いたとしたら次のようになっていた筈です。

|      |     |      |     |      |     |      |     |
| ---- | --- | ---- | --- | ---- | --- | ---- | --- |
| パン |     | パン |     | パン |     | パン |     |
| １   | ・  | ２   | ・  | ３   | ・  | ４   | ・  |

しかしこれと同じことを半ブロック早く行ったらどうなるでしょうか。

|     |      |     |      |     |      |     |      |     |
| --- | ---- | --- | ---- | --- | ---- | --- | ---- | --- |
|     | パン |     | パン |     | パン |     | パン |     |
| １  | ・   | ２  | ・   | ３  | ・   | ４  | ・   | １  |

この様に全て拍が・に来るようになりました。そして全ての数字が**裏拍（オフビート）**に来るようになりました。

**オフビート**に数字を割り当ててオフビートの数を数えること…それが**オフビートカウント**です。

オフビートカウントの最大の特徴は速いリズムでも半分の速度で数えることができることです。８分音符の速いパッセージがあっても４分音符と同じ速度で数えることができます。つまり４分音符を数えるだけで８分音符と同じスピードを得ることができます。

このオフビートカウントをテコの様に使うことでスピード感のある安定したグルーヴを創りだしていくことができます。

練習 好きな音楽に合わせて数えてみましょう。

### 協力グルーヴとは

ここで**協力グルーヴ**について説明したいと思います。**協力グルーヴ**は全てのカウントの基礎になるものです。

#### 協力グルーヴの基本

これまでは全ての拍を１人で演奏してきました。

<table>
<tbody>
<tr>
<td>１<br />
（ワン）</td>
<td>２<br />
（ツー）</td>
<td>３<br />
（スリー）</td>
<td>４<br />
（フォー）</td>
</tr>
</tbody>
</table>

しかしもしこれを２人で協力して演奏したらどうでしょうか。

<table>
<tbody>
<tr>
<td>１<br />
（ワン）</td>
<td>・</td>
<td>３<br />
（スリー）</td>
<td>・</td>
</tr>
<tr>
<td>・</td>
<td>２<br />
（ツー）</td>
<td></td>
<td>４<br />
（フォー）</td>
</tr>
</tbody>
</table>

このように分担することで各人が半分の速度で拍を演奏することができるでしょう。このことを**協力グルーヴ**と呼びます。現代あるポップス音楽のリズムは必ず**協力グルーヴ**です。

協力グルーヴを単独で演奏するときは**それぞれの音がもともと違う人が演奏している**ということを忘れないようにします。つまり音色を変えたり、アクセントを変えたり、違う音程を使ったりするようにしましょう。この様に単独の演奏者で協力グルーヴを演奏することを**独力グルーヴ**と呼びます。

基本的に**独力グルーヴ**は特殊なテクニックです。2人以上が協力しあうことで効率よくリズムを演奏する ─── それがグルーヴの本質です。つまり基本的に単独でグルーヴを起こすことはできません。

#### 協力グルーヴの歴史

かつてドラムセットがなかった頃は、打楽器１つを1人が担当しみなで協力しあって演奏していました。協力グルーヴは、こうして大勢で協力しあってグルーヴを起こすところから生まれています。 ─── この[ビデオ](https://www.youtube.com/watch?v=4htoAvgFq_g)でドラムセットの歴史が解説されていますが、ドラムセットの歴史はそのままジャズの歴史と言って良い程にジャズと密接に関連しています。ドラムセットの発達により、独力で複雑なリズムを起こすことが出来るようになり、即興演奏が発達しました。こうして複雑な協力グルーヴを独力で演奏する演奏者が現れ、結果としてスイングというリズムが生まれました。 ─── 今では協力グルーヴを独力で起こすのは珍しいことではなくなりました。しかしそれはもともとは特殊なテクニックなのです。

#### 協力グルーヴとオフビートカウント

オフビートカウントはつまり『自分の声』と『手拍子』の２者によって協力グルーヴを発生させているということができます。

### 単独リズム

協力グルーヴでないリズムを**単独リズム**と呼びます。協力のないリズムはグルーヴではないため、グルーヴとは呼びません。

### 拍の呼び方について

#### 拍（ディヴィジョン）下位拍（サブディヴィジョン）

次の様に何も分割されていない一定の時間があったとします。

|        |
| ------ |
| ・・・ |

このことを**小節**と呼びます。

この小節を次のように一定数で分割したとします。

|     |     |     |     |
| --- | --- | --- | --- |
| １  | ２  | ３  | ４  |

このことを**拍**（**ディヴィジョン**）と呼びます。

更に各拍を一定数で分割することを考えます。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
| １  | ・  | ２  | ・  | ３  | ・  | ４  | ・  |

この分割された後の拍のことを**下位拍**（**サブディヴィジョン**）と呼びます。

#### オンビート／オフビート

いくつかの拍を交互に２分類したとき、前に現れる方の拍を**表拍**・**オンビート**と呼び、後に現れる方の拍を**裏拍**・**オフビート**と呼ぶことにします。

次のように４拍あったとします。

|     |     |     |     |
| --- | --- | --- | --- |
| １  | ２  | ３  | ４  |

これを交互に２分類します。

|     |     |     |     |
| --- | --- | --- | --- |
| １  | ・  | ３  | ・  |
| ・  | ２  |     | ４  |

この時、前に現れる方をオンビート・後に現れる方をオフビートと呼びます。つまり１・３拍がオンビートで２・４がオフビートになります。

つまりサブディヴィジョンから見た時のオフビートに数字を割り当てているので**オフビートカウント**と呼んでいます。

### 頭合わせリズムと尻合わせリズム

次節以降でオフビートカウント練習をはじめます。オフビートカウント練習の目標は先にもお話した通り、**頭合わせリズム**を脱して**尻合わせリズム**を維持できるようになることです。頭合わせリズムと尻合わせリズムには、とてもはっきりした形状の違いがあります。

#### 形状の違いはどこ？

４つの拍があるとします。その中で１回だけ手を叩くとします。

|        |     |     |     |
| ------ | --- | --- | --- |
| １     | ２  | ３  | ４  |
| タン！ |     |     |     |

恐らく多くの方が１拍目で手を叩くでしょう。では、もしここで更にもう１回・合計２回手を叩くとしたらどうでしょうか。ほとんどの方が次のように手を叩くのではないでしょうか。

|        |        |     |     |
| ------ | ------ | --- | --- |
| １     | ２     | ３  | ４  |
| タン！ | タン！ |     |     |

基本となる音の**後に音を配置**しました ─── 大変に残念なことですが、このリズムの配置は聞く人にとって大変に予想しやすく眠気を誘うことになってしまうでしょう。これが**頭合わせリズム**です。

では、どのようにすれば聞く人の予想を裏切り目を覚まさせることができるのでしょうか。

|        |        |     |     |     |
| ------ | ------ | --- | --- | --- |
| ４     | １     | ２  | ３  | ４  |
| タン！ | タン！ |     |     |     |

基本となる音の**前に音を配置**しました ─── この配置では聞く人の予想よりも早く音がやってくる為、聞く人にとって予想しづらく、聞く人の目を覚まします。これが**尻合わせリズム**です。

もし頭合わせと尻合わせでそれぞれ３回手を叩くとしたら次のようになるでしょう。

|          |     |     |     |     |     |     |     |     |
| -------- | --- | --- | --- | --- | --- | --- | --- | --- |
| 拍       | １  | ２  | ３  | ４  | １  | ２  | ３  | ４  |
| 頭合わせ |     |     |     |     | ◎   | ◯   | ◯   |     |
| 尻合わせ |     |     | ◯   | ◯   | ◎   |     |     |     |

この様に**常に始まりの音を合わせることでリズムを構成するのが頭合わせリズム**の特徴です。そして**常に終わりの音を合わせることでリズムを構成するのが尻合わせリズム**の特徴です。

頭合わせは演奏の開始地点さえ合っていればよい為、リズムを演奏し始める際に予め計画を立てる必要がありません。しかし尻合わせは演奏の終了地点を合わせる必要があるため、リズムを演奏し始める際にこれから何拍のリズムを演奏するのか予め計画を立てておく必要があります。

つまり**尻合わせは頭合わせよりも演奏の時に考えなければいけない要素が多く**なります。

まず現在のその瞬間の位置から『尻』までの距離を正確に感じ取っている必要がありあます。これが尻合わせリズムをマスターする為にカウント練習が必要になる理由です。

次に、この距離感を元にして、どの様なリズムの割りかたにするのかを考えながら演奏することになるでしょう。

このように演奏中に瞬間的に思考しながら演奏する**演奏思考力**を高めるのがカウント練習の目標です。

#### 具体例を見てみよう

頭合わせと尻合わせの違いを具体例として示したビデオをいくつかご用意しました。

|                                                           |                                                               |                                                         |
| --------------------------------------------------------- | ------------------------------------------------------------- | ------------------------------------------------------- |
| [桃太郎さん](https://www.youtube.com/watch?v=qkCjf_hKgbo) | [ロックンロール](https://www.youtube.com/watch?v=-mHk5FfhFas) | [カリプソ](https://www.youtube.com/watch?v=BvpIcUBT418) |

####  実例を見てみよう

インパクトの強い音楽はしばしば尻合わせリズムでできています。

尻合わせで高インパクトな曲と言えばまずこれです。

[ベートーベンの運命](https://www.youtube.com/watch?v=jv2WJMVPQi8)です。 最初の３つの音が先駆けて入り最後の１音で尻合わせするリズムになっています。

[矢野顕子 – ラーメンたべたい](https://www.youtube.com/watch?v=eNwZVRBJy58) 。高インパクトなリズムが印象の曲です。

ジャズの即興ラインはほとんどが尻合わせリズムでできています。曲によってはテーマが最初から尻合わせリズムでできている曲も有ります。

[Duke Ellington - In A Mellow Tone](https://www.youtube.com/watch?v=1MjIiLx1Nw0)

この曲のリズムも尻合わせで構成されています。

## 基礎練習

### オンビートカウント

まずは基本としてオンビートカウントを練習します。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
| １  | ＆  | ２  | ＆  | ３  | ＆  | ４  | ＆  |

練習 好きな音楽に合わせて数えてみましょう。  
練習時間目標３時間

### 小節入りオンビートカウント

オンビートカウントに慣れてきたら小節入りカウントの練習を行いましょう。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
| １  | ＆  | ２  | ＆  | ３  | ＆  | ４  | ＆  |
| ２  | ＆  | ２  | ＆  | ３  | ＆  | ４  | ＆  |
| ３  | ＆  | ２  | ＆  | ３  | ＆  | ４  | ＆  |
| ４  | ＆  | ２  | ＆  | ３  | ＆  | ４  | ＆  |

練習 好きな音楽に合わせて数えてみましょう。  
練習時間目標３時間

### オフビートカウント（単純８分オフビート）

オンビートカウントと比べて大きく難易度があがります。

#### 正しい例

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     |     |     |     |     |     |     | １  |
| ・  | ２  | ・  | ３  | ・  | ４  | ・  | １  |

注意すべき点をいくつか挙げます。

#### 間違った例

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
| ・  | １  | ・  | ２  | ・  | ３  | ・  | ４  |

これがオフビートカウントで最もよくある失敗です。『・』よりも数字を先に数えることはとても難しい ─── それがオフビートカウント最大の難関です。注意を怠るとすぐに感覚がずれてしまい、上記のように『・』よりも数字を後に数えてしまいます。数字が後になってしまわない様に最大の注意を払う必要があります。

８分音符を先に！４分音符は後に！

練習１ 好きな音楽に合わせて数えてみましょう。(20時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(20時間)  
練習３ 自分で演奏しながら数えてみましょう。(20時間)

### オフビートカウント（基本形／８分オフビート）

２拍目４拍目に「＆」を入れたオフビートカウントです。このカウント法がオフビートカウント練習の基本型になります。今後の練習で様々なかたちで繰り返し表れますので、ここできちんと学んでおきましょう。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     |     |     |     |     |     |     | １  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | １  |

練習１ 好きな音楽に合わせて数えてみましょう。(20時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(20時間)  
練習３ 自分で演奏しながら数えてみましょう。(20時間)

### オンビートカウント（４分オフビート）

４分音符オフビートを先に数える練習です。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     |     |     |     |     |     | ４  | ・  |
| １  | ・  | ２  | ・  | ３  | ・  | ４  | ・  |

声として出てくるカウントは通常のオンビートカウントと全く同じです。しかし飽くまでも**心の中で４を先に数える**ことをはっきりと意識してカウントして下さい。例えば、音楽に合わせてカウントするときに心の中で『１・２・３・４・』と数えるのではなく、飽くまでも『４・１・２・３・』という順番で数えましょう。

練習１ 好きな音楽に合わせて数えてみましょう。(20時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(20時間)  
練習３ 自分で演奏しながら数えてみましょう。(20時間)

### オフビートカウント（４分オフビート）

４分音符オフビートを先に数える練習です。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     |     |     |     |     |     | ＆  | １  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | １  |

４拍目の位置に＆が来ます。この＆が先にくる感覚をはっきりと意識しながらカウントしましょう。音楽にあわせて「＆１・２＆３・４＆１」とはっきり意識しながら数えてみます。

慣れるまでは次のように数えても構いません。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     |     |     |     |     |     | ＆  | １  |
| ・  | ・  | ＆  | ３  | ・  | ・  | ＆  | １  |

２拍４拍以外を省略しました。「＆１・・＆３・・」と数えます。こうして２拍４拍に精神を集中することで、４拍が１拍に先行し・２拍が３拍に先行している感覚をしっかりと心に焼き付けましょう。

練習１ 好きな音楽に合わせて数えてみましょう。(20時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(20時間)  
練習３ 自分で演奏しながら数えてみましょう。(20時間)

### オフビートカウント（４分８分オフビート）

同時に４分音符オフビートと８分音符オフビートを先に数える練習です。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     |     |     |     |     | ４  | ＆  | １  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | １  |

音楽にあわせて『４＆１・２＆３・』とはっきり意識しながら数えてみます。４拍目の位置に『＆』が来ます。更にその『＆』に先駆けて『４』が入ります。『１』よりも『＆』が先にくる感覚、及び『＆』よりも『４』が先に入る感覚をはっきりと意識しながらカウントしましょう。

練習１ 好きな音楽に合わせて数えてみましょう。(20時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(20時間)  
練習３ 自分で演奏しながら数えてみましょう。(20時間)

### オンビートカウント（２分４分オフビート）

同時に２分音符オフビートと４分音符オフビートを先に数える練習です。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     |     | ２  | ・  | ３  | ・  | ４  | ・  |
| １  | ・  | ２  | ・  | ３  | ・  | ４  | ・  |

声として出てくるカウントは通常のオンビートカウントと全く同じです。しかし飽くまでも**心の中で２３４を先に数える**ことをはっきりと意識してカウントして下さい。音楽に合わせてカウントするときに心の中で『１・２・３・４・』と数えるのではなく、飽くまでも『２・３・４・１・』という順番で数えましょう。

練習１ 好きな音楽に合わせて数えてみましょう。(20時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(20時間)  
練習３ 自分で演奏しながら数えてみましょう。(20時間)

### オフビートカウント（２分４分８分オフビート）

２分音符・４分音符・８分音符のオフビートを同時に先に数える練習です。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     | ２  | ＆  | ３  | ・  | ４  | ＆  | １  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | １  |

音楽にあわせて『２＆３・４＆１・』とはっきり意識しながら数えてみます。『４＆１』よりも『２＆３』が先にくる感覚をはっきりと意識しながらカウントしましょう。

練習１ 好きな音楽に合わせて数えてみましょう。(20時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(20時間)  
練習３ 自分で演奏しながら数えてみましょう。(20時間)

### オフビートカウント（全２分４分８分オフビート）

全音符・２分音符・４分音符・８分音符のオフビートを同時に先に数える練習です。

|     |     |     |     |     |     |     |        |
| --- | --- | --- | --- | --- | --- | --- | ------ |
|     |     |     |     |     |     |     | １     |
| ・  | ２  | ・  | ３  | ・  | ４  | ・  | （２） |
| ・  | ２  | ・  | ３  | ・  | ４  | ・  | （１） |

これは完全に８分音符オフビートと同じかたちです。しかし１小節一回り先に進んでいる点が異なります。長いオフビートを正確に認識するためには**小節入りカウント**を使う必要が有ります。**小節入りカウント**は次節以降で練習します。ここでは音楽にあわせて『１・２・３・４・』が１小節早いことをはっきり意識しながら数えてみます。

練習１ 好きな音楽に合わせて数えてみましょう。(20時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(20時間)  
練習３ 自分で演奏しながら数えてみましょう。(20時間)

### 小節数入りオフビートカウント

まずはオフビートカウントと小節数カウントを同時に行うこと自体に慣れる練習をしましょう。以降の練習では、小節数入りオフビートカウントを基本形として利用します。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     |     |     |     |     |     |     | １  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ２  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ３  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ４  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ５  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ６  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ７  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ８  |

練習１ 好きな音楽に合わせて数えてみましょう。(3時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(3時間)  
練習３ 自分で演奏しながら数えてみましょう。(20時間)しながら数えてみましょう。(3時間)  

### オフビートカウント（小節オフビート）

以降では全音符以上のオフビートの練習に入ります。１小節前からリズムを開始していることを表すために８小節目からカウントを開始します。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     |     |     |     |     |     |     | ８  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | １  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ２  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ３  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ４  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ５  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ６  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ７  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ８  |

練習１ 好きな音楽に合わせて数えてみましょう。(20時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(20時間)  
練習３ 自分で演奏しながら数えてみましょう。(20時間)

### オフビートカウント（小節＋４分音符オフビート）

小節オフビートと同様ですが、『＆』（４分音符）を『８』よりも先に数えることを意識しながら練習します。

|     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- |
|     |     |     |     |     |     | ＆  | ８  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | １  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ２  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ３  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ４  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ５  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ６  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ７  |
| ・  | ２  | ＆  | ３  | ・  | ４  | ＆  | ８  |

『＆８』から始めるのと同様に

- 『＆８』から始める
- 『４＆８』から始める
- 『２＆３・４＆８』から始める

それぞれのパターンも練習します。

練習１ 好きな音楽に合わせて数えてみましょう。(200時間)  
練習２ ２拍４拍でメトロノームを鳴らしながら数えてみましょう。(200時間)  
練習３ 自分で演奏しながら数えてみましょう。(200時間)

## 仕上げ練習

これまでの練習でメトロノームを２拍４拍に鳴らしながら練習してきました。メトロノームを２拍４拍に鳴らして楽器を演奏したり声を出したりすることで充分２拍４拍の位置を確認することができた筈です。

それでは、これまでにやってきた練習をメトロノーム２拍４拍ではなく１拍3拍にあわせて再度やってみましょう。これまでメトロノームで確認していた２拍４拍の打点をメトロノームに頼らずに楽器だけで示す練習をしましょう。

注意点はメトロノームを１拍3拍に鳴らした時、２拍４拍を演奏する自分の楽器音が先に聞こえる様にはっきりと意識することです。1拍3拍でメトロノームを鳴らす場合、少しでも油断するとすぐに１拍3拍が先に鳴っている様に聞こえてきてしまいます。１拍3拍が先に聞こえないように最新の注意を払いましょう。

またなるべくメトロノームの１拍3拍と重なって楽器を演奏しないようにしましょう。飽くまでもメトロノーム音と自分の楽器音で**協力グルーヴ**を構成するように注意します。

(800時間)

## まとめ

声を出してカウントする ─── それがそのままグルーヴになります。声出しカウントが上達すればグルーヴが向上します。グルーヴが向上すると、楽器を手にしていなくてもグルーヴします。そして楽器を手にすれば楽器でもグルーヴするようになります。練習していないのに楽器が上達する ─── 声出しカウントとはそんな不思議さがあります。

声出しカウントを極めれば誰でもグルーヴします。

その気持ちが確かに伝わる熱いグルーヴを生みだします。

みんなで一緒に**激しくグルーヴしましょう！**

オカアツシ
