---
title: オフビートカウントの正しい発音方法
created: 2025-05-29T03:42
tags:
  - foo
---

この節ではオフビートカウントをする時の適切な発音方法について学びます。 

## オフビートカウントと音韻学

### リズム習得が得意な人と苦手な人が分かれるのは何故か

８分音符１つ分はやくカウントするオフビートカウントを練習すると、すぐにできようになる人と、長期間に渡ってなかなかできないままの人の２つに分かれます。「リズム感がある」「リズム感がない」と言ってしまえばそれまでですが、この様な大きな個人差が現れる理由を説明する為の仮説がいくつか存在します。

###  母国語とリズムの関係

その仮説のひとつは「その人が母国語として話すネイティブ方言による」というものです。オフビートカウントは、現在北海道から九州まで日本全国に興味を持って練習している有志がいらっしゃいます。 オフビートカウントの考案者である岡敦は、日本の様々な地域の人にオフビートカウントの練習をお手伝いする機会がありました。そこで岡敦は、オフビートカウントがすぐ出来る人とすぐ出来ない人には、強い地域性が現れることに気付いたのです。

この理由は、オフビートカウントを考案した２０１８年頃から長い間に渡って謎とされていました。

### オフビートカウントの副作用＝英語リスニング能力向上

そもそもグルーヴのトレーニング方法として生まれたオフビートカウントですが、この練習を継続すると英語のリスニング能力が向上するという現象が観測されていました。


ここから、その人が話す方言に英語に近い要素がある人はすぐに出来る様になるが、その人が話す方言に英語に近い要素がない人はなかなか出来るようにならないという説明が生まれました。もちろん、この仮説には実証がありませんでした。

### オフビートカウントと言語リズム練習

後に、岡敦がオフビートカウントを教える方法を試行錯誤していた２０２４年のある日、どんなにオフビートカウントで悪戦苦闘している人でも、末子音と頭子音のリンキングに注目し、特に**侵襲的末子音(Intrusive Consonant)** カウントに必要な全ての発音を順番にひとつひとつ教えると、その教えた直後だけはオフビートカウントが出来るようになるということに気付いたのです。

更にその訓練を行った直後だけは音楽がグルーヴするようになる事にも観察されました。

─── つまり、これは、オフビートカウント自体が英語の発音の何らかの非常に良い訓練法になっているということを示唆していました。 しかしこれも経験的に観察された現象で、具体性のある理論的根拠を持っていませんでした。

### オフビートカウントの音韻学との出会い

2025年に岡敦は**音韻学**と出会いました。そして音韻学はオフビートカウントの理論的な特性をとても良く説明してくれる事に気付いたのです。

オフビートカウントがすぐ出来る様になる人とならない人の違いが現れる理由はネイティブ言語にある ─── 音韻学はこの仮説を補強するもうひとつの説として、その人が話す方言に**ストレス拍** がある場合はオフビートカウントを直ぐに出来る用になるが、その人が話す方言に**ストレス拍** がない場合は、直ぐに出来るようにならないという説を与えてくれました。ここでは、この仮説を**オフビートカウントのストレス拍関連説**と呼びます。

どんなにオフビートカウントで悪戦苦闘している人でも、頭子音末子音のリンキングに注目して練習することでオフビートカウントが出来るようになりグルーヴする ─── この事柄を音韻学に基づいて説明すると、英語の発音規則の中でも最も重要な規則といえる **頭子音最大化原則(MOP=Maximize Onset Principle)**  と **頭音節最大化原則(MPOP=Maximal Prosodic Onset Principle)** の２つにはっきりと意識を向ける訓練を行うことで、シラブル拍とストレス拍が持つ **等時性 (Isochrony)** を身につけることが出来る ─── という説明が出来る事に気付いたのです。

 ─── つまり、これは、オフビートカウント自体がMOP/MPOPの非常に良い訓練法になっているということを示唆しています。

つまり、音韻学に基づいた訓練を行うことで、必ずオフビートカウントが出来るようになり、音楽的グルーヴ演奏能力ついても後天的に習得することが可能と言えます。

### オフビートカウントの効果

オフビートカウントの効果は依然としてはっきりと定量化されて実証されたわけではありません。しかし感覚的な結果として、**言語リズムに関する何らかの要素を開眼させるはっきりとした効果** があり、トレーニングを続けることで **見えてくる何か** があります。

我々が音楽活動をする上でぶつかる様々なリズム上の問題を少ない矛盾で説明してくれる非常に性能の良いツールになるということは、少なくとも言える筈です。

そしてまたオフビートカウントは、グルーヴという得体の知れない音楽的現象を感覚的に理解する大きな手がかりを与えてくれるということが、少なくとも言えます。

それだけでなく、これまでがむしゃらに練習する以外に何の指針もなかった英語のリスニングトレーニングに一定の指針を与えてくれるということも、少なくとも言えるでしょう。

### まとめ

この章では、岡敦が経験的に効果があることに気付いた音韻学に基づいた訓練方法を説明致します。

(続く)

