
## Content Pages (% Done / Progress since 08/17 update)

- [tatenori-theory](tatenori-theory)   --- 100%
- [beat-orientation](beat-orientation)  --- 100%
- [offbeat-count-theory](offbeat-count-theory) --- 80%
- [offbeat-count-phonetics](offbeat-count-phonetics)  --- 30%
- [metadivision-theory](metadivision-theory) --- 50%
- [three-to-n-groove-theory](three-to-n-groove-theory) --- 40%
- [distributed-groove-theory](distributed-groove-theory) --- 100%
- [weak-beat-as-sun-strong-beat-as-earth](weak-beat-as-sun-strong-beat-as-earth) --- 30%
- [offbeat-count-polyrhythm](offbeat-count-polyrhythm)  --- 80%
- [tatenori-and-psychology](tatenori-and-psychology) --- 50%
- [mechanism-behind-tatenori](mechanism-behind-tatenori) --- 10%
- [influence-of-japanese-language-on-cognition](influence-of-japanese-language-on-cognition) --- 0%

- 過去に書いた記事を読み返して見ると、私は「何故声出しカウントをすべきか」から始まり「２重オフビートカウント」「３重オフビートカウント」と多重化を増やして、更に３拍子、３拍子の２重、３拍子の３重（3^n カウント）…と順に複雑化に対応してきたことがわかった。これも想定より遥かに長い。[link](https://x.com/ats4u/status/1952049357894959578)
- polyrhythm は ダビディバカウントから複製した。内容がだいぶ古いので大幅な加筆訂正または再作成が必要。広告対応後に行う。 Tue, 19 Aug 2025 06:25:29 +0900

