---
title: 縦乗りのメカニズム
format: html
execute:
  enabled: true
  echo: false
  output: true
  eval: true
  cache: false
title-block: false
---

## 縦乗りのメカニズム


### モーラ拍ネイティブが陥りがちなリズム習癖

<div class="center-box"><blockquote class="twitter-tweet" data-media-max-width="560"><p lang="ja" dir="ltr">縦乗りと横乗りの違いを完全に把握した。縦乗り解釈する時に音符の位置がずれる。これがいわゆる『日本人の頭重心リズム』のメカニズムだ。<br><br>縦乗り（モーラ拍リズム）<br>横乗り（ストレス拍リズム）<a href="https://twitter.com/hashtag/%E3%82%AA%E3%83%95%E3%83%93%E3%83%BC%E3%83%88%E3%81%A7%E6%80%9D%E8%80%83%E3%81%99%E3%82%8B%E8%AA%9E%E5%AD%A6?src=hash&amp;ref_src=twsrc%5Etfw">#オフビートで思考する語学</a> <a href="https://t.co/o3RILE8EMy">pic.twitter.com/o3RILE8EMy</a></p>&mdash; 岡敦/Ats🇯🇵 (@ats4u) <a href="https://twitter.com/ats4u/status/1930932283294544307?ref_src=twsrc%5Etfw">June 6, 2025</a></blockquote></div>

### 縦乗りに気付く

貴方は、誰かとペアになってその人と交互に手を叩くことは出来ますでしょうか。「何をそんな簡単なことを」とおっしゃるかも知れません。しかしこれは実際にやってみると非常に難しいことだとお気付きになることと思います。

もしかするとメトロノームに合わせて交互に手を叩くことは出来るかも知れません。しかし人間が相手の場合、その手拍子の感覚は揺れ動きます。この様な揺れ動くリズムを相手にして交互に手を叩くことは、とても難しいこととお気付きになるかも知れません。

次にメトロノームを**弱拍**に合わせて即興演奏や特定の楽曲を演奏することは出来ますでしょうか。ここでいう弱拍とは、4分音符でしたら2拍目／4拍目のことです。或いは8分音符でしたら2拍4拍6拍8拍のことです。この弱拍にメトロノームを合わせて演奏することは出来ますでしょうか ─── これは更に難しいことだとお気付きになると思います。

もしかしたら「そんな難しいことは出来ないのが当然だ！」と仰るかも知れません ─── しかしここに、日本語を母国語とする人だけが持っている特殊な時間認識の偏りを観察出来るのです。

弱拍にメトロノームを鳴らすことは決して簡単なことではありませんが、日本語以外の言語を母国語とする人…特に英語を母国語とする人は、これを多少練習すれば習得することが出来るのです。しかし日本語を母国語とする人は長い年月 ─── 場合によっては20年近い年月を要することも稀ではありません。

これにははっきりした理由があります ─── その違いは言語によるリズム認識の違いにあります。

### 交互手叩き不可能性

縦乗りの人は、時間の認識の原理上「2人で交互に手を叩くことが出来ない」という特徴があります。 もしかするとメトロノームに合わせて交互に手を叩くことは出来るかも知れません。しかし不正確な人間を相手に交互に手を叩くことが出来ません。

しかし、相手が人間の場合、人間のリズムには微妙な揺らぎがあることから、その揺らぎに対して柔軟に対応する必要が発生します。つまり交互にリズムを合わせ続けるには「相手のゆらぎを感じ取りながら、自分のタイミングを調整する」という、より複雑な時間感覚が求められます。 ─── この人間同士で交互手叩きを行う場面で、時間認識の違いをはっきりと観察できる現象が観察出来るのです。

縦乗りの人は、時間認識の原理上、一定の間隔で鳴っているパルスと距離を取って同時ではない状態を維持することがとても難しく、結果として、人間同士での即時的なリズムのやりとり──すなわち交互に手を叩くような行為──が出来ないという現象となって観察されます。

一方縦乗りの人は、交互に手を叩くことは出来ませんが、不規則になっている手拍子に合わせて同時に叩くことなら即座に行う事ができます。これはむしろ、縦乗りの人に特徴的な能力で縦乗りの人以外には出来ない行為です。

これは些細なこと…と思われるかも知れません。しかし、ロック・ジャズ・クラシック・ファンク問わず、2人の奏者が交互に音を出すリズムが繰り返し現れることには注意が必要です。西洋音楽の最も基礎にバスドラムとスネアドラムを交互に演奏するリズムが現れます。特に現代あるアメリカ起源のポピュラー音楽は必ずこのリズムが登場します。

### 強拍先行は存在しない

『強弱』の様に聴こえるリズムでも、そこに隠れた暗黙の弱拍を演奏してから強拍を演奏します。海外の音楽には強拍先行は存在しません。一瞥すると強拍が先行する様に見えるリズムでも、実はその前に休符として先に弱拍を演奏する習慣があります。

### リズム解釈の違い
この言語自体が持っているリズム認識の違いは、同じ単語の発音の解釈の違いとして現れます。

| 拍リズム     | バナナ                  | コンピューター    | チョコレート   | カメラ     |
| :----------- | :---------------------- | ----------------- | -------------- | ---------- |
| モーラ拍 🇯🇵   | /**ba**-**na**-**na** / | /ko-m-pyu-u-ta-a/ | /cho-ko-re-to/ | /ka-me-ra/ |
| シラブル拍🇪🇸🇫🇷 | /**ba**-**na**-**na** / | /com-pyu-ter/     | /cho-co-late/  | /ca-me-ra/ |
| ストレス拍🇺🇸🇬🇧 | /ba-**NA**-**na** /     | /kəm-ˈPYU-ter/    | /ˈCHOK-lət/    | /KAM-ruh/  |

このリズム解釈の違いは、言語だけでなく、音楽での強拍と弱拍の前後関係の違いとして現れます。この認識の違いは、即興演奏時や作曲時の無意識の音符の配置の仕方にはっきりとした偏りを生み出します。そしてこの認識の違いは、音楽だけにとどまらず日常的に行う動作と動きの認識、行動全体に対して大きな影響を与えています。

 特にこのリズム認識の違いは、無意識の内に音楽を演奏する時の強拍弱拍の順序の違いとして現れます。

### 強拍弱拍は単独では存在しない
前述の通り強拍と弱拍が存在するためには、当たり前なことですが、最低でも２つ以上の音符が必要です。この事は特筆に値します。海外の音楽には必ず強拍弱拍があります。これは裏を返すと、単独の拍を単独で演奏することがほとんどないということを隠喩しています。 単独の拍を単独で演奏している様に見えても、演奏者及び聴者は、そこに暗黙の弱拍があることを聴き取っています。

しかし日本語のようなモーラ拍リズムの言語を母国語とする人は、しばしば音楽を演奏する時に音符を単独で演奏する習慣を持っています。ここから日本語話者は音符を聞いた時、そこに暗黙の弱拍があることは愚か、そこに強弱の区別がある事にすら気付かないという、日本語話者に独特な盲点が生まれます。

**強拍弱拍は単独では存在できなません。** そして海外の音楽では**単独の音符は存在しません。** このことをここで指摘すると共に今後常にこのことを喚起していく必要があるでしょう。

強拍でも弱拍でもない単独の音符が現れてしまう ─── これがモーラ拍リズム（日本語）話者が持っている１つ目の盲点です。

### 拍リズムによって頭合わせ尻合わせの違いが生まれるメカニズム
#### モーラ拍リズムのリボ払い
#### シラブル拍リズムの月末締め一括払い

### 桃太郎さん現象について
### 最初に聴こえた拍が１拍目強拍に聞こえる症候群について


<!--
盆踊り・マクドナルド
<div class="center-box"><iframe style="width:100%;height:360px;" src="https://www.youtube.com/embed/zhGnuWwpNxI?si=rmaaGup-ewVlmkTv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>

<div class="center-box"><blockquote class="twitter-tweet" data-media-max-width="560"><p lang="ja" dir="ltr">【外人が演奏する縦乗り】この方は日本語のリズムと英語のリズムの違いに気付いている ── が見事なまでに縦乗りに失敗している。これは彼が日本語話者でないことを表している。リエゾンによって倒置するオフビートがあり、オンビートは全てレイドバックして遅れている。<br><br> <a href="https://t.co/5MrK0hKUHo">https://t.co/5MrK0hKUHo</a> <a href="https://t.co/oJnPHqAaza">pic.twitter.com/oJnPHqAaza</a></p>&mdash; 岡敦/Ats🇯🇵 (@ats4u) <a href="https://twitter.com/ats4u/status/1573036257588178944?ref_src=twsrc%5Etfw">September 22, 2022</a></blockquote></div>
-->

