

## 弱拍天動説と弱拍地動説 {#weakbeat-geocentrism-vs-heliocentrism}

弱強リズム認識を持つ人（＝ストレス拍リズム言語を母国語として話す人）は、リズムニュアンスを演奏する時に、弱拍位置を基準位置として固定し強拍位置を移動することでニュアンスを醸し出す習慣を持っています。

<div class="center-box"><blockquote class="twitter-tweet" data-media-max-width="560"><p lang="ja" dir="ltr">レイドバックの基本『オフビートの位置は固定。オンビートの位置が遅れる』 ギターの方がこの演奏中でそれをはっきり行っています。<br><br>これを日本人が聴くとオンビートの位置が固定でオフビートの位置が早くなったように錯覚するため、同じ様に演奏することが出来ません。 <a href="https://twitter.com/hashtag/%E3%82%AA%E3%83%95%E3%83%93%E3%83%BC%E3%83%88%E3%81%A7%E6%80%9D%E8%80%83%E3%81%99%E3%82%8B%E8%AA%9E%E5%AD%A6?src=hash&amp;ref_src=twsrc%5Etfw">#オフビートで思考する語学</a> <a href="https://t.co/QC9uaA2F4h">pic.twitter.com/QC9uaA2F4h</a></p>&mdash; 岡敦/Ats🇯🇵 (@ats4u) <a href="https://twitter.com/ats4u/status/1650000173932900352?ref_src=twsrc%5Etfw">April 23, 2023</a></blockquote></div>

一方、強弱リズム認識を持つ人（＝モーラ拍リズム言語を母国語として話す人）は、リズムニュアンスを演奏する時に、弱強リズム認識を持つ人と全く逆に、強拍位置を基準位置として固定し弱拍位置を移動することでニュアンスを醸し出す習慣を持っています。

<div class="center-box"><blockquote class="twitter-tweet" data-media-max-width="560"><p lang="ja" dir="ltr">ずれのない歯ざわりのよい頭拍。朗々と歌うレイドバック。渋みと哀愁 ─── 演歌の素晴らしさがつまっている。<br><br>氷川きよしのずんどこ節<a href="https://t.co/xKDWfdwEC3">https://t.co/xKDWfdwEC3</a> <a href="https://t.co/nN06TRy28c">pic.twitter.com/nN06TRy28c</a></p>&mdash; 岡敦/Ats🇯🇵 (@ats4u) <a href="https://twitter.com/ats4u/status/1710928577670336908?ref_src=twsrc%5Etfw">October 8, 2023</a></blockquote> </div>

> なお日本の演歌では、伴奏側が強拍位置を基準位置を固定する役割を担い、歌唱者はその固定した強拍位置に対して、自分自身の演奏する強拍と弱拍の両方を移動することでニュアンスを演奏するという習慣があります。これは弱拍の位置が必ず固定になる弱強リズム認識と大きく異なる特徴です。この事については後述します。


この時、強弱リズム認識を持っている人は、この弱強リズム認識を持っている人のリズム認識を正しく認識することが出来ないという現象が起こります。

強弱リズム認識の人が弱強リズム認識のニュアンスが理解出来ない様子はあたかも、天体の動きを天動説で捉えると理解が困難になる様子とにています。

<div class="center-box"><blockquote class="twitter-tweet" data-media-max-width="560"><p lang="ja" dir="ltr">『ジャズのリズムはオフビートが基準点！』<br>オフビート基準点 ⇔ オンビート基準点<br><br>オンビートを基準にして考えると、基準点自体が動いてしまうことから、音符ずれの動きが全て矛盾して見えてしまう。オフビートを基準点にして考えると、とても単純に解釈できる。 <a href="https://t.co/muwn40MxLD">pic.twitter.com/muwn40MxLD</a></p>&mdash; 岡敦/Ats🇯🇵 (@ats4u) <a href="https://twitter.com/ats4u/status/1520578075490418688?ref_src=twsrc%5Etfw">May 1, 2022</a></blockquote></div>

弱拍の位置が基準になっていることに気付けば全ては単純な動作に見えますが、強拍位置が基準になっていると認識していると途端に全てが複雑な動作となって見えてきます。

移動しているのは、自分が足をおいている強拍だった ─── それに気付く瞬間はまるで、天動説の人々が太陽が動いていると思っていたものが、実は自分たちが立っている地球自身が動いていると気付く瞬間ととても似ています。




<div class="center-box"><blockquote class="twitter-tweet" data-media-max-width="560"><p lang="ja" dir="ltr">ストレス拍リズム（英語）のスイング ─── ベースが1/9早めのタイミングに移動しライドシンバルの8分弱拍が4分音符に対して5/9の位置に配置されている。また4分音符は全て1/9遅れている。 <a href="https://twitter.com/hashtag/%E3%82%AA%E3%83%95%E3%83%93%E3%83%BC%E3%83%88%E3%81%A7%E6%80%9D%E8%80%83%E3%81%99%E3%82%8B%E8%AA%9E%E5%AD%A6?src=hash&amp;ref_src=twsrc%5Etfw">#オフビートで思考する語学</a> (訂正版) <a href="https://t.co/QajecpWuqP">pic.twitter.com/QajecpWuqP</a></p>&mdash; 岡敦/Ats🇯🇵 (@ats4u) <a href="https://twitter.com/ats4u/status/1932739193438146682?ref_src=twsrc%5Etfw">June 11, 2025</a></blockquote></div>


<div class="center-box"><blockquote class="twitter-tweet" data-media-max-width="560"><p lang="ja" dir="ltr">モーラ拍リズム（日本語）のスイング ─── 俗に「頭重心」「縦乗り」という。ライドシンバルの4分音符が基準位置になっているため移動しない。ベースが1/32 遅めのタイミングに移動し遅れる等々、全ての打点が4分音符よりも後ろに遅れて配置され音量が小さい。 <a href="https://twitter.com/hashtag/%E3%82%AA%E3%83%95%E3%83%93%E3%83%BC%E3%83%88%E3%81%A7%E6%80%9D%E8%80%83%E3%81%99%E3%82%8B%E8%AA%9E%E5%AD%A6?src=hash&amp;ref_src=twsrc%5Etfw">#オフビートで思考する語学</a> <a href="https://t.co/KMnIJYQXmC">pic.twitter.com/KMnIJYQXmC</a></p>&mdash; 岡敦/Ats🇯🇵 (@ats4u) <a href="https://twitter.com/ats4u/status/1932139175647850918?ref_src=twsrc%5Etfw">June 9, 2025</a></blockquote></div>


<div class="center-box"><blockquote class="twitter-tweet" data-media-max-width="560"><p lang="ja" dir="ltr">欧米／東南アジアの交互に手を叩く「交互ルール」リズムに対して、真逆のルール「同時ルール」で歌う演歌。演歌のリズムの起源は中国にある。日本の演歌は（実は）中国で高い人気がある。<br><br>Credit : 蒋大为 - 北国之春 <a href="https://t.co/TtRu1Sfo52">https://t.co/TtRu1Sfo52</a><a href="https://twitter.com/hashtag/%E3%82%AA%E3%83%95%E3%83%93%E3%83%BC%E3%83%88%E3%81%A7%E6%80%9D%E8%80%83%E3%81%99%E3%82%8B%E8%AA%9E%E5%AD%A6?src=hash&amp;ref_src=twsrc%5Etfw">#オフビートで思考する語学</a> <a href="https://t.co/DsjR7NPhL4">pic.twitter.com/DsjR7NPhL4</a></p>&mdash; 岡敦/Ats🇯🇵 (@ats4u) <a href="https://twitter.com/ats4u/status/1669192825442021377?ref_src=twsrc%5Etfw">June 15, 2023</a></blockquote> </div>



<div class="center-box"><blockquote class="twitter-tweet" data-media-max-width="560"><p lang="ja" dir="ltr">二葉百合子の『関東一本〆』<br><br>正統派演歌の語法<br>・ぴったりに合わせる強拍<br>・後ろにつく弱拍<br>・揺れる強拍<br><br>Credit : 二葉百合子 - 関東一本〆<a href="https://t.co/Pz122I6Hhv">https://t.co/Pz122I6Hhv</a><a href="https://twitter.com/hashtag/%E3%82%AA%E3%83%95%E3%83%93%E3%83%BC%E3%83%88%E3%81%A7%E6%80%9D%E8%80%83%E3%81%99%E3%82%8B%E8%AA%9E%E5%AD%A6?src=hash&amp;ref_src=twsrc%5Etfw">#オフビートで思考する語学</a> <a href="https://t.co/3M68PZ4gbP">pic.twitter.com/3M68PZ4gbP</a></p>&mdash; 岡敦/Ats🇯🇵 (@ats4u) <a href="https://twitter.com/ats4u/status/1669192095406628864?ref_src=twsrc%5Etfw">June 15, 2023</a></blockquote> </div>

