#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from rhythmpress.lang_ids import detect_language_ids


def _parse_conf(path: Path) -> tuple[str | None, dict[str, str]]:
    default_lang: str | None = None
    lang_paths: dict[str, str] = {}
    if not path.is_file():
        return default_lang, lang_paths

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or "=" not in line:
            continue
        k, v = line.split("=", 1)
        key = k.strip()
        value = v.strip()
        if not value:
            continue
        if key == "default_lang":
            default_lang = value.lower()
            continue
        if key.startswith("lang_path."):
            lang = key[len("lang_path.") :].strip().lower()
            if not lang:
                continue
            path_value = value
            if not path_value.startswith("/"):
                path_value = "/" + path_value
            if not path_value.endswith("/"):
                path_value += "/"
            lang_paths[lang] = path_value
    return default_lang, lang_paths


def _worker_template() -> str:
    return """/**
 * Auto-generated by rhythmpress render-worker-router
 * Cloudflare Worker: root language router
 */

function parseCookieHeader(raw) {
  const out = Object.create(null);
  if (!raw) return out;
  const parts = raw.split(";");
  for (const part of parts) {
    const idx = part.indexOf("=");
    if (idx <= 0) continue;
    const key = part.slice(0, idx).trim();
    const value = part.slice(idx + 1).trim();
    if (!key) continue;
    out[key] = decodeURIComponent(value);
  }
  return out;
}

function parseAcceptLanguage(header) {
  if (!header) return [];
  return header
    .split(",")
    .map((x) => x.trim())
    .filter(Boolean)
    .map((x) => {
      const m = x.match(/^([A-Za-z0-9-]+)(?:;q=([0-9.]+))?$/);
      if (!m) return null;
      const tag = m[1].toLowerCase();
      const q = m[2] ? Number(m[2]) : 1;
      return Number.isFinite(q) ? { tag, q } : null;
    })
    .filter(Boolean)
    .sort((a, b) => b.q - a.q)
    .map((x) => x.tag);
}

function canonicalize(tag, available) {
  if (!tag) return null;
  const t = String(tag).trim().toLowerCase();
  if (!t) return null;
  if (available.has(t)) return t;
  const base = t.split("-")[0];
  if (available.has(base)) return base;
  return null;
}

function parseRouteMap(raw) {
  if (!raw) return Object.create(null);
  try {
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== "object") return Object.create(null);
    const out = Object.create(null);
    for (const [k, v] of Object.entries(parsed)) {
      if (typeof v !== "string") continue;
      const lang = String(k).trim().toLowerCase();
      if (!lang) continue;
      let path = v.trim();
      if (!path.startsWith("/")) path = "/" + path;
      if (!path.endsWith("/")) path += "/";
      out[lang] = path;
    }
    return out;
  } catch {
    return Object.create(null);
  }
}

function noStoreRedirect(url) {
  return new Response(null, {
    status: 302,
    headers: {
      Location: url,
      "Cache-Control": "no-store",
      Vary: "Cookie, Accept-Language",
    },
  });
}

export default {
  async fetch(request, env) {
    const method = request.method.toUpperCase();
    if (method !== "GET" && method !== "HEAD") return fetch(request);

    const url = new URL(request.url);
    if (!(url.pathname === "/" || url.pathname === "/index.html")) return fetch(request);

    const langIds = String(env.LANG_IDS || "en,ja")
      .split(",")
      .map((x) => x.trim().toLowerCase())
      .filter(Boolean);
    const available = new Set(langIds);
    if (available.size === 0) return fetch(request);

    let defaultLang = String(env.DEFAULT_LANG || "").trim().toLowerCase();
    if (!available.has(defaultLang)) defaultLang = langIds[0];

    const routeMap = parseRouteMap(env.LANG_ROUTE_MAP);
    const routeFor = (lang) => routeMap[lang] || `/${lang}/`;

    const cookies = parseCookieHeader(request.headers.get("Cookie"));
    const cookieCandidate = canonicalize(cookies.rhythmpress_lang || cookies.lang || "", available);

    let preferred = cookieCandidate;
    if (!preferred) {
      const langs = parseAcceptLanguage(request.headers.get("Accept-Language"));
      for (const tag of langs) {
        const c = canonicalize(tag, available);
        if (c) {
          preferred = c;
          break;
        }
      }
    }
    if (!preferred) preferred = defaultLang;

    const targetPath = routeFor(preferred);
    const absoluteTarget = new URL(targetPath, url.origin).toString();
    return noStoreRedirect(absoluteTarget);
  },
};
"""


def _wrangler_template(lang_ids: list[str], default_lang: str, route_map: dict[str, str]) -> str:
    route_map_json = json.dumps(route_map, ensure_ascii=False, separators=(",", ":"))
    route_map_line = (
        f'LANG_ROUTE_MAP = {json.dumps(route_map_json, ensure_ascii=False)}'
        if route_map
        else '# LANG_ROUTE_MAP = "{\\"en\\":\\"/en/\\",\\"ja\\":\\"/ja/\\"}"'
    )
    lang_ids_csv = ",".join(lang_ids)
    return (
        'name = "rhythmpress-language-router"\n'
        'main = "cloudflare-language-router.generated.mjs"\n'
        'compatibility_date = "2026-03-04"\n'
        "\n"
        "# Add routes for your zone, for example:\n"
        '# routes = [{ pattern = "example.com/*", zone_name = "example.com" }]\n'
        "\n"
        "[vars]\n"
        f'LANG_IDS = "{lang_ids_csv}"\n'
        f'DEFAULT_LANG = "{default_lang}"\n'
        f"{route_map_line}\n"
    )


def _write_if_changed(path: Path, text: str) -> bool:
    try:
        old = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        old = None
    if old == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)
    return True


def _parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="rhythmpress_render_worker_router",
        description="Generate Cloudflare Worker language router files.",
    )
    p.add_argument(
        "--conf",
        default="_rhythmpress.conf",
        help="Path to rhythmpress config (default: _rhythmpress.conf).",
    )
    p.add_argument(
        "--worker-out",
        default="cloudflare-language-router.generated.mjs",
        help="Worker output path (default: ./cloudflare-language-router.generated.mjs).",
    )
    p.add_argument(
        "--wrangler-out",
        default="wrangler.language-router.generated.toml",
        help="Wrangler output path (default: ./wrangler.language-router.generated.toml).",
    )
    p.add_argument(
        "--lang-ids",
        default="",
        help="Override language IDs (comma-separated). Default: detect from _quarto-*/_metadata-* files.",
    )
    p.add_argument(
        "--default-lang",
        default="",
        help="Override default language. Default: _rhythmpress.conf default_lang or first detected language.",
    )
    p.add_argument(
        "--no-wrangler",
        action="store_true",
        help="Generate only worker file.",
    )
    p.add_argument("--quiet", "-q", action="store_true", help="Suppress informational output.")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    ns = _parse_args(sys.argv[1:] if argv is None else argv)

    conf_path = Path(ns.conf)
    detected_default, conf_route_map = _parse_conf(conf_path)

    if ns.lang_ids.strip():
        lang_ids = [
            x.strip().lower()
            for x in ns.lang_ids.split(",")
            if x.strip()
        ]
    else:
        lang_ids = detect_language_ids(Path.cwd())

    if not lang_ids:
        print(
            "[ERROR] no language IDs found; run from project root with _quarto-<lang>.yml/_metadata-<lang>.yml, or pass --lang-ids",
            file=sys.stderr,
        )
        return 2

    default_lang = (ns.default_lang.strip().lower() or (detected_default or "")).strip()
    if default_lang not in lang_ids:
        default_lang = lang_ids[0]

    worker_text = _worker_template()
    if not worker_text.endswith("\n"):
        worker_text += "\n"
    worker_out = Path(ns.worker_out)
    worker_changed = _write_if_changed(worker_out, worker_text)

    wrangler_changed = False
    if not ns.no_wrangler:
        wrangler_text = _wrangler_template(lang_ids, default_lang, conf_route_map)
        if not wrangler_text.endswith("\n"):
            wrangler_text += "\n"
        wrangler_out = Path(ns.wrangler_out)
        wrangler_changed = _write_if_changed(wrangler_out, wrangler_text)

    if not ns.quiet:
        print(
            f"[INFO] {'generated' if worker_changed else 'unchanged'}: {worker_out}"
        )
        if not ns.no_wrangler:
            print(
                f"[INFO] {'generated' if wrangler_changed else 'unchanged'}: {Path(ns.wrangler_out)}"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
